#!/usr/bin/env bash

# this script should be run as root
if [ $EUID -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

# stop on error
set -e

SCRIPT_NAME=${BASH_SOURCE[0]}
VIM_SRC_DIR=/usr/local/src/vim

echo -e "#"
echo -e "# $SCRIPT_NAME: install necessary packages"
echo -e "#"
yum install -y \
    gcc make \
    ncurses-devel \
    lua lua-devel \
    ruby ruby-devel \
    python python-devel \
    perl perl-devel perl-ExtUtils-Embed

echo -e "#"
echo -e "# $SCRIPT_NAME: download vim source"
echo -e "#"
if [ ! -e $VIM_SRC_DIR ]; then
    mkdir -p $VIM_SRC_DIR &> /dev/null
    cd $VIM_SRC_DIR
    git clone git@github.com:vim/vim.git .
else
    cd $VIM_SRC_DIR
    git pull --rebase
fi

echo -e "#"
echo -e "# $SCRIPT_NAME: build vim"
echo -e "#"
./configure --with-features=huge \
            --enable-multibyte \
            --disable-selinux \
            --enable-cscope \
            --enable-pythoninterp \
            --enable-python3interp \
            --enable-rubyinterp \
            --enable-perlinterp \
            --enable-luainterp
make -j 4
make install

echo -e "#"
echo -e "# $SCRIPT_NAME: done !"
echo -e "#"

