#!/usr/bin/env bash

# this script should be run as root
if [ $EUID -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

# stop on error
set -e

SCRIPT_NAME=${BASH_SOURCE[0]}

echo -e "#"
echo -e "# $SCRIPT_NAME: install depending packages of plugins"
echo -e "#"
yum install -y ctags python-devel python-setuptools
easy_install pip
pip install flake8

vim +BundleInstall +qall

yum install -y gcc-c++ cmake28
set +e
ln -s /usr/bin/cmake28 /usr/local/bin/cmake
cd ~/.vim/bundle/YouCompleteMe/
./install.py --clang-completer


echo -e "#"
echo -e "# $SCRIPT_NAME: done !"
echo -e "#"
