#!/usr/bin/env bash

set -e

brew install karabiner-elements

SRC_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && cd ../../  && pwd )"

source ${SCRIPT_DIR}/util_funcs.sh

mkdir -p ~/.config/karabiner/assets/complex_modifications &> /dev/null
cp -r ${SRC_DIR}/config_files/karabiner/ ~/.config/karabiner/
