#!/usr/bin/env bash

which brew >/dev/null 2>&1
exit=$?
if [ $exit -eq 0 ]; then
    echo "brew was already installed"
    exit 0
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"
brew update

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && cd ../..  && pwd )"
source $SCRIPT_DIR/util_funcs.sh
add_config_line 'eval "$(/opt/homebrew/bin/brew shellenv)"' "$HOME/.zprofile"

