#!/usr/bin/env bash

set -e

which brew >/dev/null 2>&1
exit=$?
if [ $exit -eq 0 ]; then
    echo "brew was already installed"
    exit 0
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update

