#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME=${BASH_SOURCE[0]}
SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo -e "#"
echo -e "# $SCRIPT_NAME: install depending packages of plugins"
echo -e "#"

vim +BundleInstall +qall

echo -e "#"
echo -e "# $SCRIPT_NAME: done !"
echo -e "#"
