#!/bin/bash

# this script should be run as root
if [ $EUID -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

SCRIPT_NAME=${BASH_SOURCE[0]}

CLANG_HOME=/usr/local/src/clang
SRC_DIR=$CLANG_HOME/llvm_src
BUILD_DIR=$CLANG_HOME/build
INSTALL_DIR=/usr/clang

echo -e "#"
echo -e "# $SCRIPT_NAME: install necessary packages"
echo -e "#"
apt-get install -y subversion g++ cmake build-essential libffi-dev

echo -e "#"
echo -e "# $SCRIPT_NAME: checkout llvm"
echo -e "#"
if [ ! -e $SRC_DIR ]; then
    mkdir -p $SRC_DIR
    cd $SRC_DIR
    svn co http://llvm.org/svn/llvm-project/llvm/trunk .
else
    cd $SRC_DIR
    svn update
fi

echo -e "#"
echo -e "# $SCRIPT_NAME: checkout clang"
echo -e "#"
cd $SRC_DIR/tools
if [ ! -e "clang" ]; then
    svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
else
    cd clang
    svn update
fi

echo -e "#"
echo -e "# $SCRIPT_NAME: checkout extra clang tools"
echo -e "#"
cd $SRC_DIR/tools/clang/tools
if [ ! -e "extra" ]; then
    svn co http://llvm.org/svn/llvm-project/clang-tools-extra/trunk extra
else
    cd extra
    svn update
fi

echo -e "#"
echo -e "# $SCRIPT_NAME: checkout compiler-rt"
echo -e "#"
cd $SRC_DIR/projects
if [ ! -e "compiler-rt" ]; then
    svn co http://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt
else
    cd compiler-rt
    svn update
fi

echo -e "#"
echo -e "# $SCRIPT_NAME: config build info"
echo -e "#"
mkdir -p $BUILD_DIR
cd $BUILD_DIR
$SRC_DIR/configure --enable-optimized --disable-assertions --enable-targets=host

echo -e "#"
echo -e "# $SCRIPT_NAME: start building"
echo -e "#"
make -j 4

make update

make check-all

make install

echo -e "#"
echo -e "# $SCRIPT_NAME: done !"
echo -e "#"
