#!/usr/bin/env bash

# this script should be run as root
if [ $EUID -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

# reference:
# https://docs.docker.com/install/linux/docker-ce/ubuntu/

SCRIPT_NAME=${BASH_SOURCE[0]}

echo -e "#"
echo -e "# $SCRIPT_NAME: uninstall old versions"
echo -e "#"
set +e
apt-get remove docker docker-engine docker.io containerd runc -f

echo -e "#"
echo -e "# $SCRIPT_NAME: setup repo"
echo -e "#"
set -e
apt-get update
apt-get install -y --fix-missing \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"

echo -e "#"
echo -e "# $SCRIPT_NAME: install docker ce"
echo -e "#"
apt-get update
apt-get install -y -f docker-ce

