#!/usr/bin/env bash

# this script should be run as root
if [ $EUID -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

set -e

SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})

echo -e "#"
echo -e "# $SCRIPT_NAME: install depending packages of plugins"
echo -e "#"
apt install -y python3-dev python3-pip exuberant-ctags
pip3 install flake8

vim +BundleInstall +qall

#apt install -y build-essential cmake
#cd ~/.vim/bundle/YouCompleteMe/
#python3 ./install.py --clangd-completer

echo -e "#"
echo -e "# $SCRIPT_NAME: done !"
echo -e "#"
