#!/usr/bin/env bash

git config --global color.ui true

git config --global alias.st status
git config --global alias.br branch
git config --global alias.co checkout

git config --global alias.log1 'log --pretty=format:"%Cgreen%h %Cblue%cn %Cred(%cd)%Creset: %s"'
git config --global alias.logp 'log --pretty=format:"%Cgreen%h %Cblue%cn %Cred(%cd)%Creset:%n    %Cgreen%s%Creset" --name-status'
git config --global alias.logg 'log --graph --abbrev-commit --decorate --date=relative --format=format:"%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)" --all'

git config --global alias.sub submodule

git config --global push.default current

git config --global core.editor vim
