#!/usr/bin/env bash

# this script should be run as root
if [ $EUID -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

set -e

# get options
DO_UPGADE=0
while test $# -gt 0
do
    case "$1" in
        -u|--upgrade) DO_UPGRADE=1 ;;
    esac
    shift
done

# exec
apt-get update -y
if [ "$DO_UPGRADE" == "1" ]; then
    apt-get upgrade -y
fi

