#!/usr/bin/env bash

# this script should be run as root
if [ $EUID -ne 0 ]; then
    sudo $0 $@
    exit $?
fi

set -e

SCRIPT_NAME=${BASH_SOURCE[0]}
VIM_SRC_DIR=/usr/local/src/vim

echo -e "#"
echo -e "# $SCRIPT_NAME: install necessary packages"
echo -e "#"
apt-get install -y --fix-missing \
    libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev \
    gcc python-dev ruby-dev

echo -e "#"
echo -e "# $SCRIPT_NAME: download vim source"
echo -e "#"
if [ ! -e $VIM_SRC_DIR ]; then
    mkdir -p $VIM_SRC_DIR &> /dev/null
    cd $VIM_SRC_DIR
    git clone git@github.com:vim/vim.git .
else
    cd $VIM_SRC_DIR
    git pull --rebase
fi

echo -e "#"
echo -e "# $SCRIPT_NAME: build vim"
echo -e "#"
./configure --with-features=huge \
            --enable-rubyinterp \
            --enable-pythoninterp \
            --enable-perlinterp \
            --enable-gui=gnome2 \
            --enable-cscope
make -j 4
make install

echo -e "#"
echo -e "# $SCRIPT_NAME: done !"
echo -e "#"

